name: android

on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Install workload
      run: dotnet workload install android --ignore-failed-sources 

    - name: Restore dependencies
      run: dotnet restore MagicRingBuffer.sln

    - name: Build
      run: dotnet build --no-restore -f net9.0-android

#    - name: Test
#      run: dotnet test --no-build --verbosity normal
